In [14]:
import numpy as np
import matplotlib.pyplot as plt
import construct as ut
import os
import pickle
import PcmPy as pcm
import seaborn as sns
import pandas as pd
import OptimalBattery.evaluate as ev
import Functional_Fusion.atlas_map as am
from Functional_Fusion.dataset import DataSetMDTB
from IndividualParcellation.global_config import *
import OptimalBattery.estimate as es
import OptimalBattery.util as ut
import OptimalBattery.construct as ct
import OptimalBattery.plot as plot
import OptimalBattery.estimate as et
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np
import SUITPy as suit

In [15]:
save_dir = os.path.abspath(os.path.join(os.getcwd(),'..','eval_tsvs'))
saved_file = os.path.join(save_dir, 'real_localization_multi.tsv')
D_multi = pd.read_csv(saved_file, sep='\t')

In [16]:
D_multi[D_multi['n_task'] ==4]

   n_task            metric  iteration      corr
5       4  inverse_trace_mc          0  0.162264
6       4  inverse_trace_mc          1  0.070418
7       4  inverse_trace_mc          2  0.159932
8       4  inverse_trace_mc          3  0.188840
9       4  inverse_trace_mc          4  0.359094

In [17]:
# average across iterations column
avg_corr_df = D_multi.groupby(['n_task', 'metric'])['corr'].mean().reset_index()
avg_corr_df

    n_task            metric      corr
0        3  inverse_trace_mc  0.183975
1        4  inverse_trace_mc  0.188110
2        5  inverse_trace_mc  0.241465
3        6  inverse_trace_mc  0.296006
4        7  inverse_trace_mc  0.272887
5        8  inverse_trace_mc  0.223157
6        9  inverse_trace_mc  0.136889
7       10  inverse_trace_mc  0.235980
8       12  inverse_trace_mc  0.144767
9       14  inverse_trace_mc  0.238884
10      16  inverse_trace_mc  0.276922

In [18]:
save_dir = os.path.abspath(os.path.join(os.getcwd(),'..','eval_tsvs'))
saved_file = os.path.join(save_dir, 'real_localization_single.tsv')
D_single = pd.read_csv(saved_file, sep='\t')
D_single

    threshold      corr  regiona_idx  regionb_idx single_combination
0        0.10  0.249605            2            3           [19, 28]
1        0.20  0.296918            2            3           [19, 28]
2        0.30  0.348758            2            3           [19, 28]
3        0.40  0.401160            2            3           [19, 28]
4        0.50  0.447537            2            3           [19, 28]
5        0.60  0.484629            2            3           [19, 28]
6        0.70  0.514598            2            3           [19, 28]
7        0.80  0.532093            2            3           [19, 28]
8        0.90  0.535212            2            3           [19, 28]
9        0.95  0.515895            2            3           [19, 28]
10       0.99  0.467142            2            3           [19, 28]